#ifndef LWM_DISP_H_included
#define LWM_DISP_H_included

#include "xlib.h"

#define HIDE_BUTTON XCB_BUTTON_INDEX_3
#define MOVE_BUTTON XCB_BUTTON_INDEX_2
#define RESHAPE_BUTTON XCB_BUTTON_INDEX_1

// The 'Windows' key: X calls it Mod4, and the keysym on it is Super. Holding
// it turns the client's own window into window furniture - see the gestures
// in drag.cc, and Client::GrabSuperButtons, which is what makes lwm see the
// clicks at all.
#define SUPER_MASK XCB_MOD_MASK_4
#define SUPER_MOVE_BUTTON XCB_BUTTON_INDEX_1
#define SUPER_RESIZE_BUTTON XCB_BUTTON_INDEX_2
#define SUPER_HIDE_BUTTON XCB_BUTTON_INDEX_3

// The chords: the buttons which mean something while a button 2 gesture drag
// is already running, clicked with button 2 still held down. They're the same
// two buttons as the raise and the hide above, and they mean the same two
// things, so that a drag doesn't have to be finished before the window can be
// brought to the front or put away.
#define SUPER_CHORD_RAISE_BUTTON XCB_BUTTON_INDEX_1
#define SUPER_CHORD_HIDE_BUTTON XCB_BUTTON_INDEX_3

// Holding Control as well as the Windows key selects a different gesture set
// altogether. There's only one of them so far: a click turns lwm's furniture
// on or off for the window under the pointer. It's a separate modifier rather
// than a fourth button because the plain Super gestures have taken all three,
// and because a decoration toggle is a rarer thing to want than a move.
#define SUPER_CTRL_MASK XCB_MOD_MASK_CONTROL
#define SUPER_DECORATE_BUTTON XCB_BUTTON_INDEX_1

// MOVING_BUTTON_MASK describes the bits which are set in the mouse statis mask
// value while either of the mouse buttons we can use for dragging/reshaping
// is down.
#define MOVING_BUTTON_MASK \
  (XCB_KEY_BUT_MASK_BUTTON_1 | XCB_KEY_BUT_MASK_BUTTON_2)

#define EDGE_RESIST 32

/**
 * EWMH direction for _NET_WM_MOVERESIZE
 */
enum EWMHDirection {
  DSizeTopLeft,
  DSizeTop,
  DSizeTopRight,
  DSizeRight,
  DSizeBottomRight,
  DSizeBottom,
  DSizeBottomLeft,
  DSizeLeft,
  DMove,
  DSizeKeyboard,
  DMoveKeyboard,
  // _NET_WM_MOVERESIZE_CANCEL. Clients send this to abandon a move or resize
  // they started, typically because the user pressed Escape.
  DMoveResizeCancel
};

// Dispatches one event from the queue. The event is the raw XCB one; note
// that response_type must be masked with 0x7f before comparing, since bit
// 0x80 marks an event delivered by SendEvent rather than generated by the
// server.
extern void DispatchXEvent(xcb_generic_event_t*);

// Drains and dispatches every event currently queued.
extern void ProcessPendingEvents();

// True while a DragHandler is running: the user is part-way through a mouse
// gesture, and a new gesture should not be started.
extern bool IsDragging();

class DragHandler {
 public:
  DragHandler() = default;
  virtual ~DragHandler() = default;

  virtual void Start(xcb_generic_event_t* ev) = 0;
  // Return false to cancel the action immediately.
  virtual bool Move(xcb_generic_event_t* ev) = 0;
  virtual void End(xcb_generic_event_t* ev) = 0;

  // A press of another button while this drag is running: half of a chord.
  // Return true to take it, or false to have it ignored, which is what a drag
  // with no chords in it wants - lwm never starts a second drag while one is
  // in progress.
  virtual bool ChordPress(const xcb_button_press_event_t*) { return false; }

  // A button release while this drag is running. Return true to consume it
  // and carry on dragging, which only makes sense for a button the handler
  // took the press of; returning false ends the drag, as every release did
  // before chords existed, and so is the right answer for the button the drag
  // itself started with.
  virtual bool ChordRelease(const xcb_button_release_event_t*) { return false; }
};

#endif  // LWM_DISP_H_included
