#ifndef LWM_DISP_H_included
#define LWM_DISP_H_included

#include "xlib.h"

#define HIDE_BUTTON XCB_BUTTON_INDEX_3
#define MOVE_BUTTON XCB_BUTTON_INDEX_2
#define RESHAPE_BUTTON XCB_BUTTON_INDEX_1

// The 'Windows' key: X calls it Mod4, and the keysym on it is Super. Holding
// it turns the client's own window into window furniture - see the gestures
// in drag.cc, and Client::GrabSuperButtons, which is what makes lwm see the
// clicks at all.
#define SUPER_MASK XCB_MOD_MASK_4
#define SUPER_MOVE_BUTTON XCB_BUTTON_INDEX_1
#define SUPER_RESIZE_BUTTON XCB_BUTTON_INDEX_2
#define SUPER_HIDE_BUTTON XCB_BUTTON_INDEX_3

// MOVING_BUTTON_MASK describes the bits which are set in the mouse statis mask
// value while either of the mouse buttons we can use for dragging/reshaping
// is down.
#define MOVING_BUTTON_MASK \
  (XCB_KEY_BUT_MASK_BUTTON_1 | XCB_KEY_BUT_MASK_BUTTON_2)

#define EDGE_RESIST 32

/**
 * EWMH direction for _NET_WM_MOVERESIZE
 */
enum EWMHDirection {
  DSizeTopLeft,
  DSizeTop,
  DSizeTopRight,
  DSizeRight,
  DSizeBottomRight,
  DSizeBottom,
  DSizeBottomLeft,
  DSizeLeft,
  DMove,
  DSizeKeyboard,
  DMoveKeyboard,
  // _NET_WM_MOVERESIZE_CANCEL. Clients send this to abandon a move or resize
  // they started, typically because the user pressed Escape.
  DMoveResizeCancel
};

// Dispatches one event from the queue. The event is the raw XCB one; note
// that response_type must be masked with 0x7f before comparing, since bit
// 0x80 marks an event delivered by SendEvent rather than generated by the
// server.
extern void DispatchXEvent(xcb_generic_event_t*);

// Drains and dispatches every event currently queued.
extern void ProcessPendingEvents();

class DragHandler {
 public:
  DragHandler() = default;
  virtual ~DragHandler() = default;

  virtual void Start(xcb_generic_event_t* ev) = 0;
  // Return false to cancel the action immediately.
  virtual bool Move(xcb_generic_event_t* ev) = 0;
  virtual void End(xcb_generic_event_t* ev) = 0;
};

#endif  // LWM_DISP_H_included
