# lwm, a window manager for X11
# Copyright (C) 1997-2016 Elliott Hughes, James Carter
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# This used to be generated by imake from an Imakefile. imake has no notion of
# the xcb libraries and no pkg-config integration, so during the XCB migration
# (docs/xcb-migration-plan.md) it was replaced by this hand-written Makefile.

CXX ?= g++
PKG_CONFIG ?= pkg-config

prefix ?= /usr/local
bindir ?= $(prefix)/bin
mandir ?= $(prefix)/share/man

DEFINES = -DSHAPE

# XCB does everything except text rendering. Xft is the one thing with no XCB
# port, so libX11 stays in the link purely to serve it, bridged to our XCB
# connection via x11-xcb's XGetXCBConnection. See "The one real blocker: Xft"
# in docs/xcb-migration-plan.md; dropping these two is phase 4.
PKGS = xcb xcb-icccm xcb-randr xcb-shape xcb-image xcb-xrm sm ice x11-xcb xft

# Xlib's RandR and Shape bindings. Still needed while xlib.cc's internals are
# being ported group by group (phase 3); the xcb-randr / xcb-shape entries
# above are what replace them.
PKGS += xrandr xext

PKG_CFLAGS := $(shell $(PKG_CONFIG) --cflags $(PKGS))
PKG_LIBS := $(shell $(PKG_CONFIG) --libs $(PKGS))

WARNINGS = -Wall -Werror -Wextra -Wpedantic -Wno-sign-compare
CXXFLAGS ?= -g3 -O0
ALL_CXXFLAGS = -std=c++17 $(CXXFLAGS) $(WARNINGS) $(DEFINES) $(PKG_CFLAGS)
LDLIBS = $(PKG_LIBS)
LDFLAGS ?= -g3 -rdynamic

SRCS = \
	client.cc \
	cursor.cc \
	debug.cc \
	disp.cc \
	drag.cc \
	edge.cc \
	error.cc \
	ewmh.cc \
	focus.cc \
	framegeometry.cc \
	framegeometry_test.cc \
	geometry.cc \
	geometry_test.cc \
	hider.cc \
	log.cc \
	lwm.cc \
	manage.cc \
	menulayout.cc \
	menulayout_test.cc \
	placement.cc \
	placement_test.cc \
	resource.cc \
	screen.cc \
	screenlayout.cc \
	screenlayout_test.cc \
	session.cc \
	shape.cc \
	sizelimits.cc \
	sizelimits_test.cc \
	strings.cc \
	strings_test.cc \
	test.cc \
	tests.cc \
	xdebugprint.cc \
	xfont.cc \
	xlib.cc

OBJS = $(SRCS:.cc=.o)
DEPS = $(SRCS:.cc=.d)

all: lwm

lwm: $(OBJS)
	$(CXX) $(LDFLAGS) -o $@ $(OBJS) $(LDLIBS)

# -MMD -MP writes a .d file alongside each .o, so header edits trigger the
# right rebuilds without a hand-maintained HEADERS list.
%.o: %.cc
	$(CXX) $(ALL_CXXFLAGS) -MMD -MP -c -o $@ $<

-include $(DEPS)

# The X11 boundary gate. Only xfont.cc may reach for Xlib itself (it is the
# Xft holdout), and xlib.h owns the bridge. If Xlib leaks back into the rest
# of the tree the boundary has rotted; fail loudly rather than quietly.
# xdbg.cc, ruler.cc and setvisname.cc are standalone tools, not part of lwm,
# and are deliberately exempt.
X11_ALLOWED = xfont.cc xfont.h xlib.h xlib.cc
check-x11-boundary:
	@bad=$$(grep -l 'include *[<"]X11/' $(SRCS) *.h 2>/dev/null \
	        | grep -v -x -F -e $(shell echo '$(X11_ALLOWED)' | sed 's/ / -e /g') \
	        || true); \
	if [ -n "$$bad" ]; then \
		echo "X11 headers included outside the allowed set ($(X11_ALLOWED)):" >&2; \
		echo "$$bad" >&2; \
		exit 1; \
	fi
	@echo "X11 boundary OK"

test: lwm check-x11-boundary
	./lwm -test

smoke: lwm
	./smoke_test.sh ./lwm

install: lwm
	install -d $(DESTDIR)$(bindir) $(DESTDIR)$(mandir)/man1
	install -m 755 lwm $(DESTDIR)$(bindir)/lwm
	install -m 644 lwm.man $(DESTDIR)$(mandir)/man1/lwm.1

clean:
	rm -f lwm $(OBJS) $(DEPS)

.PHONY: all clean install test smoke check-x11-boundary
