# lwm, a window manager for X11
# Copyright (C) 1997-2026 Elliott Hughes, James Carter, Phil Norman
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# This used to be generated by imake from an Imakefile. imake has no notion of
# the xcb libraries and no pkg-config integration, so during the XCB migration
# (docs/xcb-migration-plan.md) it was replaced by this hand-written Makefile.
#
# Each program lives in its own directory under src/, its objects mirror that
# layout under build/ (src/lwm/client.cc compiles to build/lwm/client.o), and
# the binaries all land in bin/. Adding another program means adding a source
# list, a package list and a link rule alongside the three that are here;
# everything below that point is shared.

CXX ?= g++
PKG_CONFIG ?= pkg-config

prefix ?= /usr/local
bindir ?= $(prefix)/bin
mandir ?= $(prefix)/share/man

SRCDIR = src
BUILDDIR = build
BINDIR = bin

DEFINES = -DSHAPE

WARNINGS = -Wall -Werror -Wextra -Wpedantic -Wno-sign-compare
CXXFLAGS ?= -g3 -O0
# -I$(SRCDIR) and nothing more: a program reaches another's headers as
# "lwm/foo.h", and within a directory the quoted includes resolve relative to
# the including file anyway. Don't be tempted to add -I$(SRCDIR)/lwm; that puts
# lwm's strings.h ahead of the system one, and libc's string.h includes
# <strings.h>.
#
# PKG_CFLAGS is set per program by the pattern-specific assignments further
# down, so this has to stay recursively expanded.
ALL_CXXFLAGS = -std=c++17 $(CXXFLAGS) $(WARNINGS) $(DEFINES) -I$(SRCDIR) \
	$(PKG_CFLAGS)
LDFLAGS ?= -g3 -rdynamic

# pkg_cflags/pkg_libs take a package list and hand back the flags for it.
pkg_cflags = $(shell $(PKG_CONFIG) --cflags $(1))
pkg_libs = $(shell $(PKG_CONFIG) --libs $(1))

# objs_for maps a program's sources to its objects: src/foo/bar.cc (or .cpp)
# becomes build/foo/bar.o.
objs_for = $(patsubst $(SRCDIR)/%,$(BUILDDIR)/%,$(addsuffix .o,$(basename $(1))))

# ---------------------------------------------------------------- lwm

# XCB does everything except text rendering. Xft is the one thing with no XCB
# port, so libX11 stays in the link purely to serve it, bridged to our XCB
# connection via x11-xcb's XGetXCBConnection. See "The one real blocker: Xft"
# in docs/xcb-migration-plan.md; dropping x11-xcb and xft is phase 4.
#
# libSM and libICE are unchanged by any of this: neither links libX11.
LWM_PKGS = xcb xcb-cursor xcb-icccm xcb-randr xcb-shape xcb-xrm sm ice \
	x11-xcb xft

# csdclient.cc, ruler.cc, setvisname.cc and xdbg.cc live in the same directory
# but are standalone tools, not part of lwm, and so aren't listed here.
LWM_SRCS = $(addprefix $(SRCDIR)/lwm/, \
	client.cc \
	client_test.cc \
	cursor.cc \
	debug.cc \
	disp.cc \
	disp_test.cc \
	drag.cc \
	drag_test.cc \
	edge.cc \
	error.cc \
	ewmh.cc \
	ewmh_test.cc \
	fakeserver.cc \
	focus.cc \
	focus_test.cc \
	framegeometry.cc \
	framegeometry_test.cc \
	geometry.cc \
	geometry_test.cc \
	gesture.cc \
	gesture_test.cc \
	hider.cc \
	icon_test.cc \
	keyboard.cc \
	keyboard_test.cc \
	log.cc \
	lwm.cc \
	manage.cc \
	menulayout.cc \
	menulayout_test.cc \
	navigate.cc \
	navigate_test.cc \
	placement.cc \
	placement_test.cc \
	realserver.cc \
	resource.cc \
	screen.cc \
	screenlayout.cc \
	screenlayout_test.cc \
	session.cc \
	shape.cc \
	sizelimits.cc \
	sizelimits_test.cc \
	strings.cc \
	strings_test.cc \
	test.cc \
	tests.cc \
	wmtest.cc \
	xdebugprint.cc \
	xbridge.cc \
	xfont.cc \
	xlib.cc)

# ---------------------------------------------------------------- gummiband

# A panel: XCB, Xft for the text and RandR to find the monitor it sits on.
# x11-xcb and xft are the Xft bridge, exactly as for lwm above: libX11 opens
# the connection because Xft needs a Display, and XCB takes the socket over.
GUMMIBAND_PKGS = xcb xcb-randr xcb-xrm x11-xcb xft

# It borrows lwm's logging, as "lwm/log.h". log.cc pulls in nothing X-related,
# so the object build/lwm/log.o (built with lwm's package flags) serves both
# programs.
GUMMIBAND_SRCS = $(SRCDIR)/gummiband/gummiband.cpp $(SRCDIR)/lwm/log.cc

# ---------------------------------------------------------------- speckeysd

# A hot key daemon. It draws nothing, so Xft never came into it and there was
# no reason to keep libX11: this is the one program here that is pure XCB.
# xcb-keysyms provides the keycode/keysym mapping XKB used to, and xkbcommon
# is there for xkb_keysym_from_name alone, which is the one thing XCB has no
# answer to (it replaces XStringToKeysym, and takes the same key names).
SPECKEYSD_PKGS = xcb xcb-keysyms xkbcommon

SPECKEYSD_SRCS = $(SRCDIR)/speckeysd/speckeysd.cpp

# ----------------------------------------------------------------

# Resolved here rather than in the rules, so pkg-config runs a fixed number of
# times per make rather than once per file compiled.
LWM_CFLAGS := $(call pkg_cflags,$(LWM_PKGS))
LWM_LIBS := $(call pkg_libs,$(LWM_PKGS))
GUMMIBAND_CFLAGS := $(call pkg_cflags,$(GUMMIBAND_PKGS))
GUMMIBAND_LIBS := $(call pkg_libs,$(GUMMIBAND_PKGS))
SPECKEYSD_CFLAGS := $(call pkg_cflags,$(SPECKEYSD_PKGS))
SPECKEYSD_LIBS := $(call pkg_libs,$(SPECKEYSD_PKGS))

LWM_OBJS = $(call objs_for,$(LWM_SRCS))
GUMMIBAND_OBJS = $(call objs_for,$(GUMMIBAND_SRCS))
SPECKEYSD_OBJS = $(call objs_for,$(SPECKEYSD_SRCS))

# Every source that goes into a program we ship, for the dependency include
# below. sort drops the duplicate log.cc.
SRCS = $(sort $(LWM_SRCS) $(GUMMIBAND_SRCS) $(SPECKEYSD_SRCS))
OBJS = $(call objs_for,$(SRCS))
DEPS = $(OBJS:.o=.d)

BINS = $(BINDIR)/lwm $(BINDIR)/gummiband $(BINDIR)/speckeysd

all: $(BINS)

$(BINDIR)/lwm: $(LWM_OBJS)
	@mkdir -p $(@D)
	$(CXX) $(LDFLAGS) -o $@ $^ $(LWM_LIBS)

$(BINDIR)/gummiband: $(GUMMIBAND_OBJS)
	@mkdir -p $(@D)
	$(CXX) $(LDFLAGS) -o $@ $^ $(GUMMIBAND_LIBS)

$(BINDIR)/speckeysd: $(SPECKEYSD_OBJS)
	@mkdir -p $(@D)
	$(CXX) $(LDFLAGS) -o $@ $^ $(SPECKEYSD_LIBS)

# Convenience aliases, so `make lwm` still does what it always did.
lwm: $(BINDIR)/lwm
gummiband: $(BINDIR)/gummiband
speckeysd: $(BINDIR)/speckeysd

# Each program compiles against its own packages. These are pattern-specific
# variables, so which set a source gets is decided by the directory it's in.
$(BUILDDIR)/lwm/%.o: PKG_CFLAGS = $(LWM_CFLAGS)
$(BUILDDIR)/gummiband/%.o: PKG_CFLAGS = $(GUMMIBAND_CFLAGS)
$(BUILDDIR)/speckeysd/%.o: PKG_CFLAGS = $(SPECKEYSD_CFLAGS)

# -MMD -MP writes a .d file alongside each .o, so header edits trigger the
# right rebuilds without a hand-maintained HEADERS list.
$(BUILDDIR)/%.o: $(SRCDIR)/%.cc
	@mkdir -p $(@D)
	$(CXX) $(ALL_CXXFLAGS) -MMD -MP -c -o $@ $<

$(BUILDDIR)/%.o: $(SRCDIR)/%.cpp
	@mkdir -p $(@D)
	$(CXX) $(ALL_CXXFLAGS) -MMD -MP -c -o $@ $<

-include $(DEPS)

# The Xlib boundary gate. Xlib and lwm's own headers both define `Window`, to
# different widths, so a translation unit may include one or the other but
# never both - and only two files get to pick Xlib: xbridge.cc, which opens
# the connection, and xfont.cc, which drives Xft. If Xlib leaks back into the
# rest of the tree the boundary has rotted; fail loudly rather than quietly.
#
# X11/SM and X11/ICE are exempt: session management lives under the same
# include prefix but is a separate library that doesn't link libX11 or define
# any of its types.
#
# speckeysd is in the gate too, for a different reason: it links no libX11 at
# all, and the way that gets lost is somebody reaching for an X11 header for a
# constant. There's nothing it could legitimately want from one.
#
# gummiband is the exception. It's on XCB as well, but it's a single file that
# includes none of lwm's headers, so nothing stops Xlib and XCB sitting side
# by side in it, and its Xft calls need them there.
X11_CHECKED = $(LWM_SRCS) $(wildcard $(SRCDIR)/lwm/*.h) $(SPECKEYSD_SRCS)
X11_ALLOWED = $(SRCDIR)/lwm/xfont.cc $(SRCDIR)/lwm/xbridge.cc
check-x11-boundary:
	@bad=$$(for f in $(X11_CHECKED); do \
	          if grep -E 'include *[<"]X11/' "$$f" 2>/dev/null \
	              | grep -qvE 'X11/(SM|ICE)/'; then echo "$$f"; fi; \
	        done \
	        | grep -v -x -F -e $(shell echo '$(X11_ALLOWED)' | sed 's/ / -e /g') \
	        || true); \
	if [ -n "$$bad" ]; then \
		echo "Xlib headers included outside the allowed set ($(X11_ALLOWED)):" >&2; \
		echo "$$bad" >&2; \
		exit 1; \
	fi
	@echo "Xlib boundary OK"

test: $(BINDIR)/lwm check-x11-boundary
	$(BINDIR)/lwm -test

smoke: $(BINDIR)/lwm
	./smoke_test.sh $(BINDIR)/lwm

# The mouse gestures, driven with xdotool on a headless Xvfb display.
ui: $(BINDIR)/lwm
	./ui_test.sh $(BINDIR)/lwm

# Struts set by a dock that was already on screen before lwm started. Also
# Xvfb; see the header comment in strut_test.sh for why the start-up ordering
# is worth a test of its own.
strut: $(BINDIR)/lwm
	./strut_test.sh $(BINDIR)/lwm

# gummiband's own tests: config in, clicks in, pixels and properties out, on
# an Xvfb display with no window manager. It has no unit tests, so this is all
# the coverage it has.
#
# Named 'gummi' rather than 'gummiband' so that 'make gummiband' still just
# builds it, as 'make lwm' does.
gummi: $(BINDIR)/gummiband
	./gummiband_test.sh $(BINDIR)/gummiband

# speckeysd's own tests: a keys file in, key presses in, the commands it runs
# out, on a two-screen Xvfb display. Also its only coverage, and the
# regression test for its XCB port.
speckeys: $(BINDIR)/speckeysd
	./speckeysd_test.sh $(BINDIR)/speckeysd

install: all
	install -d $(DESTDIR)$(bindir) $(DESTDIR)$(mandir)/man1
	install -m 755 $(BINDIR)/lwm $(DESTDIR)$(bindir)/lwm
	install -m 755 $(BINDIR)/gummiband $(DESTDIR)$(bindir)/gummiband
	install -m 755 $(BINDIR)/speckeysd $(DESTDIR)$(bindir)/speckeysd
	install -m 644 lwm.man $(DESTDIR)$(mandir)/man1/lwm.1
	install -m 644 $(SRCDIR)/gummiband/gummiband.man \
		$(DESTDIR)$(mandir)/man1/gummiband.1

clean:
	rm -rf $(BUILDDIR) $(BINDIR)

.PHONY: all clean install test smoke ui strut gummi speckeys \
	check-x11-boundary lwm gummiband speckeysd
