#include "xdebugprint.h"

#include "client.h"
#include "ewmh.h"

std::ostream& operator<<(std::ostream& os,
                         const xcb_configure_request_event_t& e) {
  os << "ConfigRequestEvent " << WinID(e.window) << " (parent "
     << WinID(e.parent) << ")";
#define OUT(flag, var)     \
  if (e.value_mask & flag) \
    os << " " #var "->" << e.var;
  OUT(XCB_CONFIG_WINDOW_X, x);
  OUT(XCB_CONFIG_WINDOW_Y, y);
  OUT(XCB_CONFIG_WINDOW_WIDTH, width);
  OUT(XCB_CONFIG_WINDOW_HEIGHT, height);
  OUT(XCB_CONFIG_WINDOW_BORDER_WIDTH, border_width);
  OUT(XCB_CONFIG_WINDOW_SIBLING, sibling);
  OUT(XCB_CONFIG_WINDOW_STACK_MODE, stack_mode);
#undef OUT
  return os;
}

std::ostream& operator<<(std::ostream& os,
                         const xcb_configure_notify_event_t& e) {
  // Bit 0x80 of response_type marks an event delivered by SendEvent rather
  // than generated by the server; that's what the capital S means here.
  os << WinID(e.window) << " " << ((e.response_type & 0x80) ? "S" : "s")
     << e.sequence << " ";
  os << Rect::FromXYWH(e.x, e.y, e.width, e.height) << ", b=" << e.border_width;
  return os;
}

std::ostream& operator<<(std::ostream& os, const diff& d) {
  bool changed = false;
#define D(x)                                            \
  do {                                                  \
    if (d.o.x != d.n.x) {                               \
      changed = true;                                   \
      os << " " #x << " " << (d.o.x ? "t->f" : "f->t"); \
    }                                                   \
  } while (false)
  D(skip_taskbar);
  D(skip_pager);
  D(fullscreen);
  D(above);
  D(below);
#undef D
  if (!changed) {
    os << " no changes (" << d.n << ")";
  }
  return os;
}

namespace {

std::string describeFocusMode(int mode) {
  switch (mode) {
#define CASE_RETURN(x) \
  case x:              \
    return #x
    CASE_RETURN(XCB_NOTIFY_MODE_NORMAL);
    CASE_RETURN(XCB_NOTIFY_MODE_GRAB);
    CASE_RETURN(XCB_NOTIFY_MODE_UNGRAB);
#undef CASE_RETURN
  }
  return "Unknown";
}

std::string describeFocusDetail(int detail) {
  switch (detail) {
#define CASE_RETURN(x) \
  case x:              \
    return #x
    CASE_RETURN(XCB_NOTIFY_DETAIL_ANCESTOR);
    CASE_RETURN(XCB_NOTIFY_DETAIL_VIRTUAL);
    CASE_RETURN(XCB_NOTIFY_DETAIL_INFERIOR);
    CASE_RETURN(XCB_NOTIFY_DETAIL_NONLINEAR);
    CASE_RETURN(XCB_NOTIFY_DETAIL_NONLINEAR_VIRTUAL);
    CASE_RETURN(XCB_NOTIFY_DETAIL_POINTER);
    CASE_RETURN(XCB_NOTIFY_DETAIL_POINTER_ROOT);
    CASE_RETURN(XCB_NOTIFY_DETAIL_NONE);
#undef CASE_RETURN
  }
  return "Unknown";
}

}  // namespace

std::ostream& operator<<(std::ostream& os, const xcb_focus_in_event_t& e) {
  os << WinID(e.event) << " (sequence: " << e.sequence
     << ") mode: " << describeFocusMode(e.mode)
     << ", detail: " << describeFocusDetail(e.detail);
  return os;
}
